easy_admin:
    entities:
        # List the entity class name you want to manage
        Product:
            class: App\Entity\Product
            form:
                fields:
                    - name
                    - description
                    - price
                    - isPublished
                    - imageName
                    - category
                    - publisher
            list:
                fields: [name, isPublished, category, publisher]
        Category:
          class: App\Entity\Category
        User:
            class: App\Entity\User
            form:
                fields:
                    - email
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: {'Administrateur':'ROLE_ADMIN','Modérateur':'ROLE_MODERATEUR'} } }
                    - firstName
                    - lastName
        Tag:
          class: App\Entity\Tag
    design:
        menu:
            - { entity: 'Product' }
            - { entity: 'User' }
            - { entity: 'Category' }
            - { entity: 'Tag' }
            - { label: 'Newsletter', route: 'newsletter_index' }
