#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_homepage:
    path: /
    controller: App\Controller\HomeController::index

app_product_show:
    path: /produit/{slug}
    controller: App\Controller\ProductController::show
    requirements:
        slug: '[a-z0-9\-]+'
    methods: ['GET']
app_logout:
    path: /logout

# Gestion des routes admin pour les utilisateurs
app_admin_user:
    resource: routes-perso/admin_user.yaml
    prefix: /admin/user
    name_prefix: admin_user_